#see https://gist.github.com/naesheim/18d0c0a58ee61f4674353a2f4cf71475
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch
    steps:
      - checkout
      - run:
          name: Find previous successful build commit
          command: ./bin/list-affected-modules.sh
