version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch
    steps:
      - checkout
      - run: 
          name: Build incremental changes
          command: | 
            set -e

            # latest commit
            LATEST_COMMIT=$(git rev-parse HEAD)

            # latest commit where path/to/folder1 was changed
            FOLDER1_COMMIT=$(git log -1 --format=format:%H --full-diff project1)

            # latest commit where path/to/folder2 was changed
            FOLDER2_COMMIT=$(git log -1 --format=format:%H --full-diff project2)

            if [ $FOLDER1_COMMIT = $LATEST_COMMIT ]; then
              ./project1/build.sh
            fi
            if [ $FOLDER2_COMMIT = $LATEST_COMMIT ]; then
              ./project1/build.sh
            fi
