#see https://gist.github.com/naesheim/18d0c0a58ee61f4674353a2f4cf71475
version: 2.1
orbs:
  compare-url: iynere/compare-url@0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch
    steps:
      - checkout
      - compare-url/reconstruct
      - run: 
          name: Build incremental changes
          command: | 
            set -e

            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)
            echo $CIRCLE_COMPARE_URL

            CHANGE_CHECKER=./.circleci/changed-since-last-commit.py
            if [[ `python3 ${CHANGE_CHECKER} ./project1` == "True" ]]; then
                ./project1/build.sh
            fi
            if [[ `python3 ${CHANGE_CHECKER} ./project2` == "True" ]]; then
                ./project2/build.sh
            fi
