version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch
    steps:
      - checkout
      - run: 
          name: Build incremental changes
          command: | 
            CHANGE_CHECKER=./.circleci/changed-since-last-commit.py
            SUB_DIR=./project1
            if [[ `python3 ${CHANGE_CHECKER} ${SUB_DIR}` == "True" ]]; then
                .project1/build.sh
            fi
