version: 2
orbs:
  compare-url: iynere/compare-url@0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch
    steps:
      - checkout
      - compare-url/reconstruct
      - run: 
          name: Build incremental changes
          command: | 
            set -e

            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)

            CHANGE_CHECKER=./scripts/changed-since-last-commit.py
            if [[ `python3 ${CHANGE_CHECKER} ./project1` == "True" ]]; then
                ./project1/build.sh
            fi
            if [[ `python3 ${CHANGE_CHECKER} ./project1` == "True" ]]; then
                ./project1/build.sh
            fi
